name: nginx Images
on:
  push:
    branches:
      - master
    paths:
      - nginx/**
      - .github/workflows/nginx-images.yml
      - .github/workflows/generic.yml
  workflow_dispatch:
jobs:
  generic:
    uses: ./.github/workflows/generic.yml
    with:
      image-name: "nginx"
      latest: "1.26"
      filters: |
        shared: &shared
          - nginx/README.md
          - .github/workflows/nginx-images.yml
          - .github/workflows/generic.yml
        nginx-1.26:
          - nginx/1.26/**
          - *shared
    secrets: inherit
