name: PHP Images
on:
  push:
    branches:
      - master
    paths:
      - php/**
      - .github/workflows/php-images.yml
      - .github/workflows/generic.yml
  workflow_dispatch:
jobs:
  generic:
    uses: ./.github/workflows/generic.yml
    with:
      image-name: "php"
      filters: |
        shared: &shared
          - php/README.md
          - .github/workflows/php-images.yml
          - .github/workflows/generic.yml
        php-7.4-cli:
          - php/7.4-cli/**
          - *shared
        php-7.4-fpm:
          - php/7.4-fpm/**
          - *shared
        php-8.0-cli:
          - php/8.0.cli/**
          - *shared
        php-8.0-fpm:
          - php/8.0-fpm/**
          - *shared
        php-8.1-cli:
          - php/8.1-cli/**
          - *shared
        php-8.1-fpm:
          - php/8.1-fpm/**
          - *shared
        php-8.2-cli:
          - php/8.2-cli/**
          - *shared
        php-8.2-fpm:
          - php/8.2-fpm/**
          - *shared
        php-8.3-cli:
          - php/8.3-cli/**
          - *shared
        php-8.3-fpm:
          - php/8.3-fpm/**
          - *shared
        php-8.4-cli:
          - php/8.4-cli/**
          - *shared
        php-8.4-fpm:
          - php/8.4-fpm/**
          - *shared
      aliases: |
        php-7.4-cli:
          - 7.4
        php-8.0-cli:
          - 8.0
        php-8.1-cli:
          - 8.1
        php-8.2-cli:
          - 8.2
        php-8.3-cli:
          - 8.3
        php-8.4-cli:
          - 8.4
          - latest
          - latest-cli
        php-8.4-fpm:
          - latest-fpm
    secrets: inherit
